### ISSUE TITLE
启用插件之后，=后面的提示不会出现.

### ISSUE THREAD

**Issue by ispinel** [xxxg0001/lua-for-vscode#2]
安装了Lua(keyring)插件和此插件.
在最新升级之后，当输入：
"a = "之后， = 符号之后的字段提示并不会出现.

卸载插件之后正常.

概率性重现.

**Comment by xxxg0001** [comment]
有可能是为了支持4.x的upvalue语法，对语法解析进行了修改导致的，迟些我安装那个插件看看,不过你说的a=之后的字段提示是什么？最好举个例子，这样才比较明白

**Comment by xxxg0001** [comment]
经过测试没有遇到这个问题

**Comment by ispinel** [comment]
Sorry好久没看，似乎我不能再从Closed状态设置成Open,我重新开一个issues说明这个问题.

感谢开发者答复;-P.
